### ISSUE TITLE
airless连接问题

### ISSUE THREAD

**Issue by 18055437709** [James-oc/JMAirKiss#1]
作者您好， 我看了你的Air kiss集成的源代码，我也试过，可以找到ssid，但是无法连接，不知道您的connection方法里面怎么写的，连接应该也需要设备IP地址吧，我很像向您请教下这个问题。如果看到，可以回复下我吗。

**Comment by xiaobs** [comment]
您好！您的设备有支持Airkiss功能吗？

**Comment by 18055437709** [comment]
您好 ，我的设备支持Air kiss的

**Comment by 18055437709** [comment]
我现在自己也完成了一部分 还差一点
