### ISSUE TITLE
源代码问题

### ISSUE THREAD

**Issue by w450434204** [James-oc/JMAirKiss#2]
源代码可以发给我一份吗？或者支付一定费用也可以。谢谢。想了解这一块知识。

**Comment by xiaobs** [comment]
您好！目前暂不能对外开放，谢谢理解！

**Comment by w450434204** [comment]
呜呜，很想了解这块代码。你是通过抓包实现的吗？

**Comment by w450434204** [comment]
非常的理解。可以加我的QQ号码吗 450434204 谢谢。或则告诉我下你的邮箱也可以。

**Comment by lazer88** [comment]
你好,想问下,demo下下来一直连不上wifi,请问还需要配置什么地方么?谢谢

**Comment by xiaobs** [comment]
您好！请问下是你的设备支持AirKiss协议吗？
